services:
  postgres:
    image: postgres:17-alpine
    container_name: hgtonline-database
    environment:
      POSTGRES_DB: hgtonline
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
